import { Tile } from '../../render/atlas';
import { BlockId, type BlockType } from './BlockType';

/** Block definitions indexed by BlockId. Air is index 0. */
export const BLOCKS: BlockType[] = [
  {
    id: BlockId.Air,
    name: 'air',
    solid: false,
    transparent: true,
    emitsLight: 0,
    tiles: { top: -1, bottom: -1, side: -1 },
    renderLayer: 'opaque',
    hardness: 0,
    soundGroup: 'stone',
    drops: BlockId.Air,
  },
  {
    id: BlockId.Stone,
    name: 'stone',
    solid: true,
    transparent: false,
    emitsLight: 0,
    tiles: { top: Tile.Stone, bottom: Tile.Stone, side: Tile.Stone },
    renderLayer: 'opaque',
    hardness: 1.5,
    soundGroup: 'stone',
    drops: BlockId.Cobblestone, // mined stone yields cobblestone (smelt back to stone)
  },
  {
    id: BlockId.Dirt,
    name: 'dirt',
    solid: true,
    transparent: false,
    emitsLight: 0,
    tiles: { top: Tile.Dirt, bottom: Tile.Dirt, side: Tile.Dirt },
    renderLayer: 'opaque',
    hardness: 0.5,
    soundGroup: 'dirt',
    drops: BlockId.Dirt,
  },
  {
    id: BlockId.Grass,
    name: 'grass',
    solid: true,
    transparent: false,
    emitsLight: 0,
    tiles: { top: Tile.GrassTop, bottom: Tile.Dirt, side: Tile.GrassSide },
    renderLayer: 'opaque',
    hardness: 0.6,
    soundGroup: 'grass',
    drops: BlockId.Dirt,
  },
  {
    id: BlockId.Sand,
    name: 'sand',
    solid: true,
    transparent: false,
    emitsLight: 0,
    tiles: { top: Tile.Sand, bottom: Tile.Sand, side: Tile.Sand },
    renderLayer: 'opaque',
    hardness: 0.5,
    soundGroup: 'sand',
    drops: BlockId.Sand,
  },
  {
    id: BlockId.Water,
    name: 'water',
    solid: false,
    transparent: true,
    emitsLight: 0,
    tiles: { top: Tile.Water, bottom: Tile.Water, side: Tile.Water },
    renderLayer: 'transparent',
    hardness: -1,
    soundGroup: 'stone',
    drops: BlockId.Air,
  },
  {
    id: BlockId.Wood,
    name: 'wood',
    solid: true,
    transparent: false,
    emitsLight: 0,
    tiles: { top: Tile.WoodTop, bottom: Tile.WoodTop, side: Tile.WoodSide },
    renderLayer: 'opaque',
    hardness: 2.0,
    soundGroup: 'wood',
    drops: BlockId.Wood,
  },
  {
    id: BlockId.Leaves,
    name: 'leaves',
    solid: true,
    transparent: true,
    emitsLight: 0,
    tiles: { top: Tile.Leaves, bottom: Tile.Leaves, side: Tile.Leaves },
    renderLayer: 'transparent',
    hardness: 0.2,
    soundGroup: 'leaves',
    drops: BlockId.Leaves,
  },
  {
    id: BlockId.Planks,
    name: 'planks',
    solid: true,
    transparent: false,
    emitsLight: 0,
    tiles: { top: Tile.Planks, bottom: Tile.Planks, side: Tile.Planks },
    renderLayer: 'opaque',
    hardness: 2.0,
    soundGroup: 'wood',
    drops: BlockId.Planks,
  },
  {
    id: BlockId.Cobblestone,
    name: 'cobblestone',
    solid: true,
    transparent: false,
    emitsLight: 0,
    tiles: { top: Tile.Cobblestone, bottom: Tile.Cobblestone, side: Tile.Cobblestone },
    renderLayer: 'opaque',
    hardness: 2.0,
    soundGroup: 'stone',
    drops: BlockId.Cobblestone,
  },
  {
    id: BlockId.CraftingTable,
    name: 'crafting table',
    solid: true,
    transparent: false,
    emitsLight: 0,
    tiles: { top: Tile.CraftingTable, bottom: Tile.Planks, side: Tile.CraftingTable },
    renderLayer: 'opaque',
    hardness: 2.5,
    soundGroup: 'wood',
    drops: BlockId.CraftingTable,
  },
  {
    id: BlockId.Furnace,
    name: 'furnace',
    solid: true,
    transparent: false,
    emitsLight: 0,
    tiles: { top: Tile.Furnace, bottom: Tile.Furnace, side: Tile.Furnace },
    renderLayer: 'opaque',
    hardness: 3.5,
    soundGroup: 'stone',
    drops: BlockId.Furnace,
  },
];
